import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import Script from "next/script";
import { fetchProjectData } from "@/lib/api";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get('host') || '';
  const subdomain = host.split('.')[0];

  let projectVariables: any[] = [];
  try {
    const projectData = await fetchProjectData(subdomain);

    if (!projectData) {
      console.error(`No project data returned for subdomain: ${subdomain}`);
    } else if (!projectData.variables) {
      console.error(`Project data returned but no variables found for subdomain: ${subdomain}`);
    } else {
      console.log(`SUCCESS: ${projectData.variables.length} variables loaded for subdomain: ${subdomain}`);
      projectVariables = projectData.variables;
    }
  } catch (error) {
    console.error(`Failed to load project data for subdomain ${subdomain}:`, error);
  }

  const cssVariables = projectVariables
    .filter((v) => v.type === 'color')
    .map(v => {
      const varName = v.key.startsWith('--') ? v.key : `--${v.key}`;
      return `${varName}: ${v.primaryValue};`;
    })
    .join('\n');


  const tailwindThemeVariables = projectVariables
    .filter((v) => v.type === 'color')
    .map(v => {
      const varName = v.key.startsWith('--') ? v.key.substring(2) : v.key;
      return `--color-${varName}: ${v.primaryValue};`;
    })
    .join('\n        ');

  console.log("THE VARIABLES:::", {
    cssVariables,
    tailwindThemeVariables,
  })

  return (
    <html lang="en">
      <head>
        <link rel="dns-prefetch" href="https://cdn.jsdelivr.net" />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" crossOrigin="anonymous" />
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <style type="text/tailwindcss">
          {`
            @theme {
            ${tailwindThemeVariables}
            }
          `}
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
