import { Variable, VariableSet } from "@/types/builder.types";

export const variableSets: VariableSet[] = [
    {
        id: "set_colors",
        name: "Colors",
        key: "colors",
    },
    {
        id: "set_radius",
        name: "Border Radius",
        key: "radius",
    }
]

export const colorVariables: Variable[] = [
    {
        id: '--background',
        name: 'Background',
        key: '--background',
        type: 'color',
        primaryValue: "#FFFFFF",
        secondaryValue: "#1D1D1F",
        variableSet: 'set_colors',
    },
    {
        id: '--foreground',
        name: 'Foreground',
        key: '--foreground',
        type: 'color',
        primaryValue: "#0A0A0A",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--card',
        name: 'Card',
        key: '--card',
        type: 'color',
        primaryValue: "#FFFFFF",
        secondaryValue: "#0A0A0A",
        variableSet: 'set_colors',
    },
    {
        id: '--card-foreground',
        name: 'Card Foreground',
        key: '--card-foreground',
        type: 'color',
        primaryValue: "#0A0A0A",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--primary',
        name: 'Primary',
        key: '--primary',
        type: 'color',
        primaryValue: "#6D3DF2",
        secondaryValue: "#6D3DF2",
        variableSet: 'set_colors',
    },
    {
        id: '--primary-foreground',
        name: 'Primary Foreground',
        key: '--primary-foreground',
        type: 'color',
        primaryValue: "#FAFAFA",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--secondary',
        name: 'Secondary',
        key: '--secondary',
        type: 'color',
        primaryValue: "#F55B00",
        secondaryValue: "#F55B00",
        variableSet: 'set_colors',
    },
    {
        id: '--secondary-foreground',
        name: 'Secondary Foreground',
        key: '--secondary-foreground',
        type: 'color',
        primaryValue: "#0F0F10",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--muted',
        name: 'Muted',
        key: '--muted',
        type: 'color',
        primaryValue: "#F5F5F6",
        secondaryValue: "#262628",
        variableSet: 'set_colors',
    },
    {
        id: '--muted-foreground',
        name: 'Muted Foreground',
        key: '--muted-foreground',
        type: 'color',
        primaryValue: "#757578",
        secondaryValue: "#A4A4A6",
        variableSet: 'set_colors',
    },
    {
        id: '--accent',
        name: 'Accent',
        key: '--accent',
        type: 'color',
        primaryValue: "#F5F5F6",
        secondaryValue: "#262628",
        variableSet: 'set_colors',
    },
    {
        id: '--accent-foreground',
        name: 'Accent Foreground',
        key: '--accent-foreground',
        type: 'color',
        primaryValue: "#0F0F10",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--destructive',
        name: 'Destructive',
        key: '--destructive',
        type: 'color',
        primaryValue: "#EF4444",
        secondaryValue: "#7F1D1D",
        variableSet: 'set_colors',
    },
    {
        id: '--destructive-foreground',
        name: 'Destructive Foreground',
        key: '--destructive-foreground',
        type: 'color',
        primaryValue: "#FAFAFA",
        secondaryValue: "#FAFAFA",
        variableSet: 'set_colors',
    },
    {
        id: '--border',
        name: 'Border',
        key: '--border',
        type: 'color',
        primaryValue: "#E4E4E7",
        secondaryValue: "#262628",
        variableSet: 'set_colors',
    },
    {
        id: '--input',
        name: 'Input',
        key: '--input',
        type: 'color',
        primaryValue: "#E4E4E7",
        secondaryValue: "#262628",
        variableSet: 'set_colors',
    },
    {
        id: '--ring',
        name: 'Ring',
        key: '--ring',
        type: 'color',
        primaryValue: "#6D3DF2",
        secondaryValue: "#6D3DF2",
        variableSet: 'set_colors',
    },
];

export const radiusVariables: Variable[] = [
    {
        id: '--radius-sm',
        name: 'Small',
        key: '--radius-sm',
        type: 'size',
        primaryValue: "0.125rem",
        secondaryValue: "0.125rem",
        variableSet: 'set_radius',
    },
    {
        id: '--radius-md',
        name: 'Medium',
        key: '--radius-md',
        type: 'size',
        primaryValue: "0.25rem",
        secondaryValue: "0.25rem",
        variableSet: 'set_radius',
    },
    {
        id: '--radius-lg',
        name: 'Large',
        key: '--radius-lg',
        type: 'size',
        primaryValue: "0.5rem",
        secondaryValue: "0.5rem",
        variableSet: 'set_radius',
    },
    {
        id: '--radius-xl',
        name: 'Extra Large',
        key: '--radius-xl',
        type: 'size',
        primaryValue: "0.75rem",
        secondaryValue: "0.75rem",
        variableSet: 'set_radius',
    },
    {
        id: '--radius-full',
        name: 'Full',
        key: '--radius-full',
        type: 'size',
        primaryValue: "9999px",
        secondaryValue: "9999px",
        variableSet: 'set_radius',
    },
];
