import { Variable, VariableSet } from "@/types/builder.types";

export const variableSets: VariableSet[] = [
    {
        id: "set_colors",
        name: "Colors",
        key: "colors",
    }
]

export const colorVariables: Variable[] = [
    {
        id: '--background',
        name: 'Background',
        key: '--background',
        type: 'color',
        primaryValue: "0 0% 100%",
        secondaryValue: "239 11% 12%",
        variableSet: 'set_colors',
    },
    {
        id: '--foreground',
        name: 'Foreground',
        key: '--foreground',
        type: 'color',
        primaryValue: "240 10% 3.9%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--card',
        name: 'Card',
        key: '--card',
        type: 'color',
        primaryValue: "0 0% 100%",
        secondaryValue: "240 10% 3.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--card-foreground',
        name: 'Card Foreground',
        key: '--card-foreground',
        type: 'color',
        primaryValue: "240 10% 3.9%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--popover',
        name: 'Popover',
        key: '--popover',
        type: 'color',
        primaryValue: "0 0% 100%",
        secondaryValue: "240 10% 3.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--popover-foreground',
        name: 'Popover Foreground',
        key: '--popover-foreground',
        type: 'color',
        primaryValue: "240 10% 3.9%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--primary',
        name: 'Primary',
        key: '--primary',
        type: 'color',
        primaryValue: "261 69% 61%",
        secondaryValue: "261 69% 61%",
        variableSet: 'set_colors',
    },
    {
        id: '--primary-foreground',
        name: 'Primary Foreground',
        key: '--primary-foreground',
        type: 'color',
        primaryValue: "0 0% 98%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--secondary',
        name: 'Secondary',
        key: '--secondary',
        type: 'color',
        primaryValue: "24 100% 48%",
        secondaryValue: "24 100% 48%",
        variableSet: 'set_colors',
    },
    {
        id: '--secondary-foreground',
        name: 'Secondary Foreground',
        key: '--secondary-foreground',
        type: 'color',
        primaryValue: "240 5.9% 10%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--muted',
        name: 'Muted',
        key: '--muted',
        type: 'color',
        primaryValue: "240 4.8% 95.9%",
        secondaryValue: "240 3.7% 15.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--muted-foreground',
        name: 'Muted Foreground',
        key: '--muted-foreground',
        type: 'color',
        primaryValue: "240 3.8% 46.1%",
        secondaryValue: "240 5% 64.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--accent',
        name: 'Accent',
        key: '--accent',
        type: 'color',
        primaryValue: "240 4.8% 95.9%",
        secondaryValue: "240 3.7% 15.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--accent-foreground',
        name: 'Accent Foreground',
        key: '--accent-foreground',
        type: 'color',
        primaryValue: "240 5.9% 10%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--destructive',
        name: 'Destructive',
        key: '--destructive',
        type: 'color',
        primaryValue: "0 84.2% 60.2%",
        secondaryValue: "0 62.8% 30.6%",
        variableSet: 'set_colors',
    },
    {
        id: '--destructive-foreground',
        name: 'Destructive Foreground',
        key: '--destructive-foreground',
        type: 'color',
        primaryValue: "0 0% 98%",
        secondaryValue: "0 0% 98%",
        variableSet: 'set_colors',
    },
    {
        id: '--border',
        name: 'Border',
        key: '--border',
        type: 'color',
        primaryValue: "240 5.9% 90%",
        secondaryValue: "240 3.7% 15.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--input',
        name: 'Input',
        key: '--input',
        type: 'color',
        primaryValue: "240 5.9% 90%",
        secondaryValue: "240 3.7% 15.9%",
        variableSet: 'set_colors',
    },
    {
        id: '--ring',
        name: 'Ring',
        key: '--ring',
        type: 'color',
        primaryValue: "261 69% 61%",
        secondaryValue: "261 69% 61%",
        variableSet: 'set_colors',
    },
];
