import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "../globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get('host') || '';
  
  // console.log('[DEBUG] Layout Headers:', Object.fromEntries(headersList.entries()));
  // console.log('[DEBUG] Layout Host header value:', host);
  
  let subdomain = 'demo'; // Default fallback subdomain
  if (host && host.includes('.')) {
    subdomain = host.split('.')[0];
  } else {
    console.warn('Could not extract subdomain from host:', host);
  }
  
  // console.log('[DEBUG] Layout resolved subdomain:', subdomain);

  let projectVariables: any[] = [];
  try {
    const apiBaseUrl = process.env.NEXT_PUBLIC_API_URL;
    const apiUrl = `${apiBaseUrl}/preview/projects/subdomain/${subdomain}/layout-variables`;
    
    const response = await fetch(apiUrl, {
      next: { 
        revalidate: 180,
        tags: [`layout-variables-${subdomain}`], 
      },
      headers: {
        'Content-Type': 'application/json',
      },
    });

    if (!response.ok) {
      if (response.status === 404) {
        console.warn(`Layout variables not found for subdomain "${subdomain}". Using default variables.`);
        // Provide default color variables for a clean look when no project exists
        projectVariables = [
          { key: 'primary', type: 'color', primaryValue: '#3b82f6' },
          { key: 'secondary', type: 'color', primaryValue: '#6366f1' },
          { key: 'accent', type: 'color', primaryValue: '#10b981' },
          { key: 'background', type: 'color', primaryValue: '#ffffff' },
          { key: 'foreground', type: 'color', primaryValue: '#1f2937' },
        ];
      } else {
        throw new Error(`Failed to fetch layout variables: ${response.statusText}`);
      }
    } else {
      const result = await response.json();
      const layoutData = result.payload;

      if (!layoutData) {
        console.error(`No layout data returned for subdomain: ${subdomain}`);
      } else if (!layoutData.variables) {
        console.error(`Layout data returned but no variables found for subdomain: ${subdomain}`);
      } else {
        projectVariables = layoutData.variables;
      }
    }
  } catch (error) {
    console.error(`Failed to load project data for subdomain ${subdomain}:`, error);
    // Provide fallback variables even when an error occurs
    projectVariables = [
      { key: 'primary', type: 'color', primaryValue: '#3b82f6' },
      { key: 'secondary', type: 'color', primaryValue: '#6366f1' },
      { key: 'accent', type: 'color', primaryValue: '#10b981' },
      { key: 'background', type: 'color', primaryValue: '#ffffff' },
      { key: 'foreground', type: 'color', primaryValue: '#1f2937' },
    ];
  }

  const tailwindThemeVariables = projectVariables
    .filter((v) => v.type === 'color')
    .map(v => {
      const varName = v.key.startsWith('--') ? v.key.substring(2) : v.key;
      return `--color-${varName}: ${v.primaryValue};`;
    })
    .join('\n        ');

  return (
    <html lang="en">
      <head>
        <Script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></Script>
        <style type="text/tailwindcss">
          {`
            @theme {
              ${tailwindThemeVariables}
            }
          `}
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
